/**
 * @solana-programs/quarry-mine
 *
 * TypeScript client for the Quarry Mine program, the core liquidity mining program of the Quarry protocol
 *
 * Generated by `bun run codegen` from programs/quarry-mine/. Do not edit.
 */

export * from "./generated/index.ts";
