name = "grill-example-dapp"
compatibility_date = "2025-06-19"

[assets]
directory = "./apps/example-dapp/dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "grill.ianm.com"
zone_name = "ianm.com"
custom_domain = true

# Build configuration
[build]
command = "bun run build"

[observability]
enabled = true
head_sampling_rate = 1
