/**
 * @solana-programs/tribeca
 *
 * TypeScript client for Tribeca governance programs (Govern and Locked Voter)
 *
 * Generated by `bun run codegen` from programs/bundles.ts. Do not edit.
 */

export * from "@solana-programs/tribeca-locked-voter";
export * from "@solana-programs/tribeca-govern";

// Names exported by more than one bundled program resolve to the program
// listed first in programs/bundles.ts.
export {
  ACTIVATE_PROPOSAL_DISCRIMINATOR,
  getActivateProposalDiscriminatorBytes,
  getActivateProposalInstruction,
  getActivateProposalInstructionDataCodec,
  getActivateProposalInstructionDataDecoder,
  getActivateProposalInstructionDataEncoder,
  parseActivateProposalInstruction,
} from "@solana-programs/tribeca-locked-voter";
export type {
  ActivateProposalInput,
  ActivateProposalInstruction,
  ActivateProposalInstructionData,
  ActivateProposalInstructionDataArgs,
  ParsedActivateProposalInstruction,
} from "@solana-programs/tribeca-locked-voter";

// Programs whose exports are shadowed above, in full under a namespace.
export * as govern from "@solana-programs/tribeca-govern";
