// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/api/index.mdx?collection=docs&hash=1755508897183"
import * as docs_4 from "../content/docs/quick-start.mdx?collection=docs&hash=1755508897183"
import * as docs_3 from "../content/docs/installation.mdx?collection=docs&hash=1755508897183"
import * as docs_2 from "../content/docs/index.mdx?collection=docs&hash=1755508897183"
import * as docs_1 from "../content/docs/configuration.mdx?collection=docs&hash=1755508897183"
import * as docs_0 from "../content/docs/api.mdx?collection=docs&hash=1755508897183"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"api.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/api.mdx"}, data: docs_0 }, { info: {"path":"configuration.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/configuration.mdx"}, data: docs_1 }, { info: {"path":"index.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/index.mdx"}, data: docs_2 }, { info: {"path":"installation.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/installation.mdx"}, data: docs_3 }, { info: {"path":"quick-start.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/quick-start.mdx"}, data: docs_4 }, { info: {"path":"api/index.mdx","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/api/index.mdx"}, data: docs_5 }], [{"info":{"path":"meta.json","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/meta.json"},"data":{"title":"Documentation","pages":["index","installation","configuration","api"]}}, {"info":{"path":"api/meta.json","absolutePath":"/Users/igm/proj/macalinao/coda/docs/content/docs/api/meta.json"},"data":{"title":"API Reference","pages":["index","cli","configuration","visitors"]}}])