import {
  accountValueNode,
  addPdasVisitor,
  constantPdaSeedNodeFromString,
  defineConfig,
  numberTypeNode,
  pdaLinkNode,
  pdaSeedValueNode,
  pdaValueNode,
  publicKeyTypeNode,
  SYSTEM_PROGRAM_VALUE_NODE,
  updateAccountsVisitor,
  updateProgramsVisitor,
  variablePdaSeedNode,
} from "@macalinao/coda";

// The IDL calls the program `squads_multisig_program`, which would generate
// names like `SQUADS_MULTISIG_PROGRAM_PROGRAM_ADDRESS`. Shorten it to `squads`.
const renameProgramVisitor = updateProgramsVisitor({
  squadsMultisigProgram: { name: "squads" },
});

// Seeds mirror the derivations shipped in the official Squads SDK
// (`@sqds/multisig@2.1.4`, `src/pda.ts`), which in turn mirror
// `SEED_*` in the on-chain program. Every seed below is a byte-for-byte
// match with that file.
//
// Numeric seeds are little-endian, matching the beet `u8`/`u32`/`u64`
// writers the SDK uses and Anchor's `to_le_bytes()` on-chain.
const addCustomPdasVisitor = addPdasVisitor({
  squads: [
    {
      name: "programConfig",
      docs: [
        "The global program config, which holds the multisig creation fee and treasury.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        constantPdaSeedNodeFromString("utf8", "program_config"),
      ],
    },
    {
      name: "multisig",
      docs: [
        "A multisig account, identified by the `createKey` used to create it.",
        "The `createKey` must sign the `multisigCreateV2` instruction, so it is",
        "typically a throwaway keypair generated by the client.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "createKey",
          publicKeyTypeNode(),
          "The key used to create the multisig",
        ),
      ],
    },
    {
      name: "vault",
      docs: [
        "A vault owned by the multisig. Vaults are the signers of the",
        "instructions inside a vault transaction, and are where a multisig's",
        "assets live. Index 0 is the default vault.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "multisig",
          publicKeyTypeNode(),
          "The multisig that owns the vault",
        ),
        constantPdaSeedNodeFromString("utf8", "vault"),
        variablePdaSeedNode(
          "index",
          numberTypeNode("u8"),
          "The vault index (0-255)",
        ),
      ],
    },
    {
      name: "transaction",
      docs: [
        "A transaction account within a multisig, identified by its index.",
        "Used for config transactions, vault transactions and batches alike.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "multisig",
          publicKeyTypeNode(),
          "The multisig that owns the transaction",
        ),
        constantPdaSeedNodeFromString("utf8", "transaction"),
        variablePdaSeedNode(
          "index",
          numberTypeNode("u64"),
          "The transaction index, starting at 1",
        ),
      ],
    },
    {
      name: "proposal",
      docs: [
        "The proposal that tracks the votes for the transaction at",
        "`transactionIndex`.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "multisig",
          publicKeyTypeNode(),
          "The multisig that owns the proposal",
        ),
        constantPdaSeedNodeFromString("utf8", "transaction"),
        variablePdaSeedNode(
          "transactionIndex",
          numberTypeNode("u64"),
          "The index of the transaction being voted on",
        ),
        constantPdaSeedNodeFromString("utf8", "proposal"),
      ],
    },
    {
      name: "batchTransaction",
      docs: [
        "An individual transaction inside a batch. `batchIndex` is the",
        "transaction index of the batch itself; `transactionIndex` is the",
        "position within that batch, starting at 1.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "multisig",
          publicKeyTypeNode(),
          "The multisig that owns the batch",
        ),
        constantPdaSeedNodeFromString("utf8", "transaction"),
        variablePdaSeedNode(
          "batchIndex",
          numberTypeNode("u64"),
          "The transaction index of the batch",
        ),
        constantPdaSeedNodeFromString("utf8", "batch_transaction"),
        variablePdaSeedNode(
          "transactionIndex",
          numberTypeNode("u32"),
          "The position within the batch, starting at 1",
        ),
      ],
    },
    {
      name: "ephemeralSigner",
      docs: [
        "An ephemeral signer belonging to a vault transaction. These are",
        "PDA signers a transaction can use for instructions that require a",
        "fresh keypair (for example, creating a new account).",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "transaction",
          publicKeyTypeNode(),
          "The transaction that owns the ephemeral signer",
        ),
        constantPdaSeedNodeFromString("utf8", "ephemeral_signer"),
        variablePdaSeedNode(
          "ephemeralSignerIndex",
          numberTypeNode("u8"),
          "The ephemeral signer index",
        ),
      ],
    },
    {
      name: "spendingLimit",
      docs: [
        "A spending limit that lets specific members move funds out of a vault",
        "without a full multisig approval.",
      ],
      seeds: [
        constantPdaSeedNodeFromString("utf8", "multisig"),
        variablePdaSeedNode(
          "multisig",
          publicKeyTypeNode(),
          "The multisig that owns the spending limit",
        ),
        constantPdaSeedNodeFromString("utf8", "spending_limit"),
        variablePdaSeedNode(
          "createKey",
          publicKeyTypeNode(),
          "The key used to create the spending limit",
        ),
      ],
    },
  ],
});

export default defineConfig({
  outputDir: "./src/generated",
  docs: {
    npmPackageName: "@solana-programs/squads",
  },
  instructionAccountDefaultValues: [
    {
      account: "systemProgram",
      defaultValue: SYSTEM_PROGRAM_VALUE_NODE,
    },
    // The program config is a singleton PDA with no variable seeds.
    {
      account: "programConfig",
      defaultValue: pdaValueNode(pdaLinkNode("programConfig"), []),
    },
    // `createKey` signs `multisigCreateV2`, so the multisig address is
    // fully determined by the accounts already on the instruction.
    {
      instruction: "multisigCreateV2",
      account: "multisig",
      defaultValue: pdaValueNode(pdaLinkNode("multisig"), [
        pdaSeedValueNode("createKey", accountValueNode("createKey")),
      ]),
    },
  ],
  visitors: [
    renameProgramVisitor,
    updateAccountsVisitor({
      programConfig: { pda: pdaLinkNode("programConfig") },
      multisig: { pda: pdaLinkNode("multisig") },
      proposal: { pda: pdaLinkNode("proposal") },
      spendingLimit: { pda: pdaLinkNode("spendingLimit") },
      // Config transactions, vault transactions and batches all live at a
      // multisig transaction index and share the same derivation.
      configTransaction: { pda: pdaLinkNode("transaction") },
      vaultTransaction: { pda: pdaLinkNode("transaction") },
      batch: { pda: pdaLinkNode("transaction") },
      vaultBatchTransaction: { pda: pdaLinkNode("batchTransaction") },
    }),
    addCustomPdasVisitor,
  ],
});
