/**
 * @solana-programs/quarry-operator
 *
 * TypeScript client for the Quarry Operator program, which delegates Quarry rewarder administration
 *
 * Generated by `bun run codegen` from programs/quarry-operator/. Do not edit.
 */

export * from "./generated/index.ts";
