/**
 * @solana-programs/mpl-token-auth-rules
 *
 * TypeScript client for the Metaplex Token Auth Rules program
 *
 * Generated by `bun run codegen` from programs/mpl-token-auth-rules/. Do not edit.
 */

export * from "./generated/index.ts";
