/**
 * @solana-programs/kamino-klend
 *
 * TypeScript client for the Kamino Lending (klend) program on its own, without Kamino Farms
 *
 * Generated by `bun run codegen` from programs/kamino-klend/. Do not edit.
 */

export * from "./generated/index.ts";
