/**
 * @solana-programs/tribeca-locked-voter
 *
 * TypeScript client for the Tribeca Locked Voter (vote escrow) program
 *
 * Generated by `bun run codegen` from programs/tribeca-locked-voter/. Do not edit.
 */

export * from "./generated/index.ts";
