/**
 * @solana-programs/goki-smart-wallet
 *
 * TypeScript client for the Goki Smart Wallet (multisig) program
 *
 * Generated by `bun run codegen` from programs/goki-smart-wallet/. Do not edit.
 */

export * from "./generated/index.ts";
