/**
 * @solana-programs/voter-stake-registry
 *
 * TypeScript client for the SPL Governance Voter Stake Registry program
 *
 * Generated by `bun run codegen` from programs/voter-stake-registry/. Do not edit.
 */

export * from "./generated/index.ts";
