/**
 * @solana-programs/kamino-farms
 *
 * TypeScript client for the Kamino Farms program
 *
 * Generated by `bun run codegen` from programs/kamino-farms/. Do not edit.
 */

export * from "./generated/index.ts";
