/**
 * @solana-programs/tribeca-govern
 *
 * TypeScript client for the Tribeca Govern program
 *
 * Generated by `bun run codegen` from programs/tribeca-govern/. Do not edit.
 */

export * from "./generated/index.ts";
