/**
 * @solana-programs/quarry-registry
 *
 * TypeScript client for the Quarry Registry program, which tracks the quarries of a rewarder
 *
 * Generated by `bun run codegen` from programs/quarry-registry/. Do not edit.
 */

export * from "./generated/index.ts";
