/**
 * @solana-programs/quarry-mint-wrapper
 *
 * TypeScript client for the Quarry Mint Wrapper program, which mints Quarry rewards through rate-limited minters
 *
 * Generated by `bun run codegen` from programs/quarry-mint-wrapper/. Do not edit.
 */

export * from "./generated/index.ts";
