/**
 * @solana-programs/spl-stake-pool
 *
 * TypeScript client for the SPL Stake Pool program
 *
 * Generated by `bun run codegen` from programs/spl-stake-pool/. Do not edit.
 */

export * from "./generated/index.ts";
