/**
 * @solana-programs/meteora-damm-v2
 *
 * TypeScript client for Meteora Damm V2 program
 *
 * Generated by `bun run codegen` from programs/meteora-damm-v2/. Do not edit.
 */

export * from "./generated/index.ts";
