/**
 * @solana-programs/orca-whirlpools
 *
 * TypeScript client for Orca Whirlpools program
 *
 * Generated by `bun run codegen` from programs/orca-whirlpools/. Do not edit.
 */

export * from "./generated/index.ts";
