import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

/** Options for {@link writeWorkspaceScaffold}. */
export interface WorkspaceScaffoldOptions {
  /** Root package name. */
  name: string;
  /** Git URL of the repository the workspace is published to. */
  repositoryUrl: string;
  /** Workspace catalog: the versions `catalog:` dependencies resolve to. */
  catalog: Record<string, string>;
  /** Root devDependencies (oxfmt, tsdown, typescript, @types/node, ...). */
  devDependencies: Record<string, string>;
  packageManager: string;
  engines: Record<string, string>;
  /** Files copied into the workspace root, e.g. a shared tsdown.config.ts. */
  copyFiles: { from: string; to: string }[];
}

/**
 * Imports every built package and fails if one does not load or exports
 * nothing. Written to `scripts/smoke-test.ts` in the generated workspace.
 */
const SMOKE_TEST = `// Generated by @macalinao/megagraph. Imports every built package.
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

async function findPackages(dir: string, depth: number): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === "node_modules") continue;
    const child = join(dir, entry.name);
    try {
      await readFile(join(child, "package.json"));
      found.push(child);
    } catch {}
    if (depth > 1) found.push(...(await findPackages(child, depth - 1)));
  }
  return found;
}

let failed = 0;
const packages = await findPackages(join(import.meta.dirname, "..", "packages"), 2);
for (const dir of packages.toSorted()) {
  const { name } = JSON.parse(await readFile(join(dir, "package.json"), "utf-8"));
  try {
    const exports = Object.keys(await import(pathToFileURL(join(dir, "dist", "index.js")).href));
    if (exports.length === 0) throw new Error("exports nothing");
    console.log(\`ok \${name} (\${exports.length} exports)\`);
  } catch (error) {
    failed++;
    console.error(\`FAIL \${name}: \${error instanceof Error ? error.message : String(error)}\`);
  }
}
console.log(\`\${packages.length - failed}/\${packages.length} packages load\`);
if (failed > 0) process.exit(1);
`;

/**
 * Writes the root of a standalone Bun workspace for generated packages:
 * `package.json` (workspaces `packages/*` and `packages/*\/*`), `.gitignore`,
 * `.gitattributes`, a smoke test and the copied shared files.
 */
export async function writeWorkspaceScaffold(
  outDir: string,
  options: WorkspaceScaffoldOptions,
): Promise<void> {
  await mkdir(join(outDir, "scripts"), { recursive: true });
  const packageJson = {
    name: options.name,
    private: true,
    type: "module",
    license: "Apache-2.0",
    author: "Ian Macalinao <me@ianm.com>",
    repository: { type: "git", url: options.repositoryUrl },
    workspaces: {
      // Umbrella packages sit at packages/<protocol>/ and program packages
      // at packages/<protocol>/<program>/.
      packages: ["packages/*", "packages/*/*"],
      catalog: options.catalog,
    },
    scripts: {
      build: "bun run --filter '@solana-programs/*' build",
      typecheck: "bun run --filter '@solana-programs/*' typecheck",
      test: "bun scripts/smoke-test.ts",
      lint: "oxfmt --check",
      format: "oxfmt",
    },
    devDependencies: options.devDependencies,
    packageManager: options.packageManager,
    engines: options.engines,
  };
  await writeFile(
    join(outDir, "package.json"),
    `${JSON.stringify(packageJson, null, 2)}\n`,
  );
  await writeFile(join(outDir, "scripts", "smoke-test.ts"), SMOKE_TEST);
  await writeFile(
    join(outDir, ".gitignore"),
    [
      "node_modules/",
      "dist/",
      ".turbo/",
      "*.tsbuildinfo",
      ".DS_Store",
      "",
    ].join("\n"),
  );
  await writeFile(
    join(outDir, ".gitattributes"),
    [
      "packages/**/src/generated/** linguist-generated=true",
      "packages/**/docs/** linguist-generated=true",
      "graph/codama.json linguist-generated=true",
      "graph/packages.json linguist-generated=true",
      "",
    ].join("\n"),
  );
  for (const { from, to } of options.copyFiles) {
    await mkdir(dirname(join(outDir, to)), { recursive: true });
    await copyFile(from, join(outDir, to));
  }
}
