import type { ProgramNode } from "codama";
import type { ProgramPackageConfig } from "./define-program.ts";

/** Keywords every generated package carries. */
const BASE_KEYWORDS = ["coda", "solana", "client", "esm", "typescript"];

/** Range of `@solana/kit` versions the generated clients support. */
const KIT_PEER_RANGE = "^6.10.0 || ^7.0.0 || ^8.0.0";

/** A package this package depends on because it links into its program. */
export interface PackageDependency {
  program: string;
  packageName: string;
}

export interface PackageTemplateInput {
  slug: string;
  version: string;
  package: ProgramPackageConfig;
  dependencies: PackageDependency[];
}

/**
 * Renders the generated `package.json`.
 */
export function renderPackageJson(input: PackageTemplateInput): string {
  const keywords = [
    ...new Set([...BASE_KEYWORDS, ...(input.package.keywords ?? [])]),
  ];
  const packageJson = {
    name: input.package.name,
    version: input.version,
    description: input.package.description,
    type: "module",
    sideEffects: false,
    author: "Ian Macalinao <me@ianm.com>",
    homepage: "https://coda.ianm.com",
    license: "Apache-2.0",
    keywords,
    main: "dist/index.js",
    types: "dist/index.d.ts",
    exports: {
      ".": {
        import: "./dist/index.js",
        types: "./dist/index.d.ts",
      },
    },
    files: ["dist/", "src/"],
    scripts: {
      build: "tsdown",
      clean: "rm -fr dist/ node_modules/ tsconfig.tsbuildinfo",
    },
    ...(input.dependencies.length > 0 && {
      dependencies: Object.fromEntries(
        input.dependencies
          .map((dependency) => dependency.packageName)
          .toSorted()
          .map((name) => [name, "workspace:^"]),
      ),
    }),
    peerDependencies: {
      "@solana/kit": KIT_PEER_RANGE,
      "@solana/program-client-core": KIT_PEER_RANGE,
    },
    devDependencies: {
      "@macalinao/tsconfig": "catalog:",
      "@solana/kit": "catalog:",
      "@solana/program-client-core": "catalog:",
      tsdown: "catalog:",
      typescript: "catalog:",
    },
    publishConfig: {
      access: "public",
    },
    repository: {
      type: "git",
      url: "git+https://github.com/macalinao/coda.git",
      directory: `clients/${input.slug}`,
    },
  };
  return `${JSON.stringify(packageJson, null, 2)}\n`;
}

/**
 * Renders the generated `tsconfig.json`.
 */
export function renderTsconfig(): string {
  return `${JSON.stringify(
    { extends: "@macalinao/tsconfig/tsconfig.base.json" },
    null,
    2,
  )}\n`;
}

/**
 * Renders the doc comment at the top of the generated `src/index.ts`.
 */
export function renderEntryHeader(
  input: PackageTemplateInput,
  source: string,
): string {
  return [
    "/**",
    ` * ${input.package.name}`,
    " *",
    ` * ${input.package.description}`,
    " *",
    ` * Generated by \`bun run codegen\` from ${source}. Do not edit.`,
    " */",
  ].join("\n");
}

/**
 * Renders the generated `src/index.ts` entry barrel of a program package.
 */
export function renderEntryBarrel(input: PackageTemplateInput): string {
  return [
    renderEntryHeader(input, `programs/${input.slug}/`),
    "",
    'export * from "./generated/index.ts";',
    "",
  ].join("\n");
}

/**
 * Renders the generated `README.md`. `body` is the optional hand-written
 * `programs/<slug>/README.md`, inserted after the installation section.
 */
export function renderReadme(
  input: PackageTemplateInput,
  program: ProgramNode,
  docsFile: string,
  body: string | null,
): string {
  const { name, description } = input.package;
  const sections = [
    `# ${name}`,
    `[![npm version](https://img.shields.io/npm/v/${name}.svg)](https://www.npmjs.com/package/${name})`,
    description,
    `<!-- Generated by \`bun run codegen\` from programs/${input.slug}/. Edit programs/${input.slug}/README.md instead. -->`,
    [
      "## Installation",
      "",
      "```bash",
      `bun add ${name} @solana/kit`,
      "```",
    ].join("\n"),
  ];
  if (body !== null && body.trim().length > 0) {
    sections.push(body.trim());
  }
  sections.push(
    [
      "## Program",
      "",
      `- Name: \`${program.name}\``,
      `- Address: \`${program.publicKey}\``,
      `- Reference: [${docsFile}](./${docsFile})`,
    ].join("\n"),
  );
  if (input.dependencies.length > 0) {
    sections.push(
      [
        "## Linked programs",
        "",
        "This program links to nodes of the following programs. Their generated code is imported from their own packages rather than duplicated here:",
        "",
        ...input.dependencies.map(
          (dependency) =>
            `- \`${dependency.program}\`: [\`${dependency.packageName}\`](https://www.npmjs.com/package/${dependency.packageName})`,
        ),
      ].join("\n"),
    );
  }
  sections.push(
    [
      "## License",
      "",
      "Copyright © 2025 Ian Macalinao",
      "",
      "Licensed under the Apache License, Version 2.0",
    ].join("\n"),
  );
  return `${sections.join("\n\n")}\n`;
}

/**
 * Renders the generated `README.md` of an umbrella package.
 */
export function renderBundleReadme(
  input: PackageTemplateInput,
  conflicts: string[],
  namespaces: PackageDependency[],
): string {
  const { name, description } = input.package;
  const sections = [
    `# ${name}`,
    `[![npm version](https://img.shields.io/npm/v/${name}.svg)](https://www.npmjs.com/package/${name})`,
    description,
    "<!-- Generated by `bun run codegen` from programs/bundles.ts. Do not edit. -->",
    [
      "## Installation",
      "",
      "```bash",
      `bun add ${name} @solana/kit`,
      "```",
    ].join("\n"),
    [
      "## Included programs",
      "",
      "This package contains no code of its own: it re-exports everything from the following packages, which can also be installed individually:",
      "",
      ...input.dependencies.map(
        (dependency) =>
          `- \`${dependency.program}\`: [\`${dependency.packageName}\`](https://www.npmjs.com/package/${dependency.packageName})`,
      ),
    ].join("\n"),
  ];
  if (conflicts.length > 0) {
    sections.push(
      [
        "## Name conflicts",
        "",
        `${conflicts.length.toString()} name(s) are exported by more than one of these programs. The flat export resolves to the program listed first above; the other programs are also exported in full under a namespace:`,
        "",
        ...namespaces.map(
          (namespace) =>
            `- \`${namespace.program}\` (\`import { ${namespace.program} } from "${name}"\`)`,
        ),
      ].join("\n"),
    );
  }
  sections.push(
    [
      "## License",
      "",
      "Copyright © 2025 Ian Macalinao",
      "",
      "Licensed under the Apache License, Version 2.0",
    ].join("\n"),
  );
  return `${sections.join("\n\n")}\n`;
}
