/**
 * @solana-programs/quarry-redeemer
 *
 * TypeScript client for the Quarry Redeemer program, which redeems IOU tokens for their underlying tokens
 *
 * Generated by `bun run codegen` from programs/quarry-redeemer/. Do not edit.
 */

export * from "./generated/index.ts";
