/**
 * @solana-programs/spl-governance
 *
 * TypeScript client for the SPL Governance program
 *
 * Generated by `bun run codegen` from programs/spl-governance/. Do not edit.
 */

export * from "./generated/index.ts";
