/**
 * @solana-programs/goki-token-signer
 *
 * TypeScript client for the Goki Token Signer program, which lets an NFT holder sign for a PDA derived from the NFT's mint
 *
 * Generated by `bun run codegen` from programs/goki-token-signer/. Do not edit.
 */

export * from "./generated/index.ts";
