/**
 * @solana-programs/quarry-merge-mine
 *
 * TypeScript client for the Quarry Merge Mine program, which stakes one deposit across multiple quarries
 *
 * Generated by `bun run codegen` from programs/quarry-merge-mine/. Do not edit.
 */

export * from "./generated/index.ts";
