/**
 * @solana-programs/kamino-lending
 *
 * TypeScript client for the Kamino Lending and Kamino Farms programs
 *
 * Generated by `bun run codegen` from programs/bundles.ts. Do not edit.
 */

export * from "@solana-programs/kamino-klend";
export * from "@solana-programs/kamino-farms";

// Names exported by more than one bundled program resolve to the program
// listed first in programs/bundles.ts.
export {
  getUpdateGlobalConfigAdminDiscriminatorBytes,
  getUpdateGlobalConfigAdminInstruction,
  getUpdateGlobalConfigAdminInstructionDataCodec,
  getUpdateGlobalConfigAdminInstructionDataDecoder,
  getUpdateGlobalConfigAdminInstructionDataEncoder,
  getUpdateGlobalConfigDiscriminatorBytes,
  getUpdateGlobalConfigInstruction,
  getUpdateGlobalConfigInstructionDataCodec,
  getUpdateGlobalConfigInstructionDataDecoder,
  getUpdateGlobalConfigInstructionDataEncoder,
  parseUpdateGlobalConfigAdminInstruction,
  parseUpdateGlobalConfigInstruction,
  UPDATE_GLOBAL_CONFIG_ADMIN_DISCRIMINATOR,
  UPDATE_GLOBAL_CONFIG_DISCRIMINATOR,
} from "@solana-programs/kamino-klend";
export type {
  ParsedUpdateGlobalConfigAdminInstruction,
  ParsedUpdateGlobalConfigInstruction,
  UpdateGlobalConfigAdminInput,
  UpdateGlobalConfigAdminInstruction,
  UpdateGlobalConfigAdminInstructionData,
  UpdateGlobalConfigAdminInstructionDataArgs,
  UpdateGlobalConfigInput,
  UpdateGlobalConfigInstruction,
  UpdateGlobalConfigInstructionData,
  UpdateGlobalConfigInstructionDataArgs,
} from "@solana-programs/kamino-klend";

// Programs whose exports are shadowed above, in full under a namespace.
export * as farms from "@solana-programs/kamino-farms";
