/**
 * @solana-programs/kamino-lending
 *
 * TypeScript client for the Kamino Lending program
 *
 * Generated by `bun run codegen` from programs/kamino-lending/. Do not edit.
 */

export * from "./generated/index.ts";
